name: advent_of_code
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

flutter: 
  assets:
    - assets/aoc2022_input_files/
    - assets/aoc2023_input_files/
    - assets/aoc2025_input_files/

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  freezed_annotation: ^3.1.0
  meta: ^1.17.0
  retrieval: ^1.0.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.4
  lints: ^6.0.0
  test: ^1.28.0
